name: Flask CI

on:
  push:
    branches: [main]

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version:
          - "3.12"
    name: "test"
    runs-on: ${{ matrix.os }}

    steps:
    - name: "Checkout code"
      uses: "actions/checkout@v2"
      with:
        python-version: ${{ matrix.python-version }}

    - name: "Install dependencies"
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: "Create docker image"
      run: |
        docker run --name some-mongo -d mongo:4.4.24

    - name: Start MongoDB
      uses: MongoCamp/mongodb-github-action@1.0.0
      with:
        mongodb-version: "8.0"

    - name: Run tests
      run: pytest