name: Flask CI

on:
  push:
    branches: [main]

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version:
          - "3.12"
    name: "test"
    runs-on: ${{ matrix.os }}

    steps:
    - name: "Checkout code"
      uses: "actions/checkout@v2"
      with:
        python-version: ${{ matrix.python-version }}

    - name: "Install dependencies"
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r ../../backend/requirements.txt
        
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.11.0
      with:
        mongodb-version: "8.0-rc-jammy"

    - name: Run tests
      run: pytest